### ISSUE TITLE
Transfer ownership of the npm package to Isotoma

### ISSUE THREAD

**Issue by plumdog** [isotoma/sops-secretsmanager-cdk#27]
Currently, my user is the only maintainer of the npm package (and the key used to publish from CI is mine).

We should create/find an Isotoma npm user, add them as a maintainer, and replace my key in CI with one from that account.

**Comment by plumdog** [comment]
@winjer Does an Isotoma npm user exist? If so, what is the username, if not, can you create one - so I can add them as a maintainer?

**Comment by winjer** [comment]
will add you to the org.
